apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-deployment
  labels:
    app: recipe-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recipe-app
  template:
    metadata:
      labels:
        app: recipe-app
    spec:
      containers:
      - name: nginx
        image: #image#
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: recipe-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: recipe-app